write-kubeconfig-mode: "0644"
tls-san:
  - "192.168.100.10"
node-label:
  - "foo=bar"
  - "something=amazing"
#server: "https://192.168.100.10:6443"
node-ip: "192.168.100.11"
kube-controller-manager-arg:
- "pod-eviction-timeout=1m"
- "node-monitor-period=2s"
- "node-monitor-grace-period=16s"
kubelet-arg:
- "node-status-update-frequency=4s"
kube-apiserver-arg: 
- "default-not-ready-toleration-seconds=20"
- "default-unreachable-toleration-seconds=20"